apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rwcv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-rwcv@sha256:b0053af699ef97a2bfd0a806b93f28af04653a5b41e3d1cda00c1b6b4f5f040d
        name: my-nodejs
        resources: {}
status: {}
